### ISSUE TITLE
Container Native Load Balancing Umbrella Issue

### ISSUE THREAD

**Issue by freehan** [kubernetes/ingress-gce#583]
This is the umbrella issue for container native load balancing, aka network endpoint group (NEG). 

Current Known Issues: 

- [X] [readiness probe not reflected on health check when NEG is enabled](https://github.com/kubernetes/ingress-gce/issues/541)

- [x] [NEG Programming Latency](https://cloud.google.com/kubernetes-engine/docs/how-to/container-native-load-balancing#align_rollouts)

- [x] [Disruption caused by 0->1, 1->0 transitions](https://cloud.google.com/kubernetes-engine/docs/how-to/container-native-load-balancing#scale-to-zero_workloads_interruption)

- [ ] [May leak NEG resource when cluster is deleted](https://cloud.google.com/kubernetes-engine/docs/how-to/container-native-load-balancing#incomplete_garbage_collection)

- [ ] [NEG cannot be enabled for default backend service](https://github.com/kubernetes/ingress-gce/issues/767)

**Comment by autrilla** [comment]
For the [NEG Programming Latency](https://cloud.google.com/kubernetes-engine/docs/how-to/container-native-load-balancing#align_rollouts) issue, even with `minReadySeconds` and `terminationGracePeriodSeconds` set to 180, I'm still seeing a small amount of 502s during rollouts. Is this expected? My test was during a rollout of 11 pods, sending 100 requests per second to them overall. I saw 96 502s over the course of the rollout.

I'd like to understand the cause of this issue. My current guess is that Kubernetes terminates the pod and stops routing traffic to it, but the NEG is updated *after* the pod is terminated. If so, could we perhaps solve this with a pre-stop hook that detaches the pod from the NEG before terminating?

**Comment by bowei** [comment]
@autrilla can you file a new issue for your bug? This is a tracking issue for feature dev...

**Comment by autrilla** [comment]
Sure, done!
