### ISSUE TITLE
L7-ILB Support Tracking

### ISSUE THREAD

**Issue by spencerhance** [kubernetes/ingress-gce#731]
Issue for tracking progress of adding support for the L7-ILB to ingress.  

Current planned updates (will be updated as scope/requirements change):
- [x] Generate composite types for relevant services
  - [x] Update k8s-cloud-provider to have all regional types - https://github.com/GoogleCloudPlatform/k8s-cloud-provider/pull/9
  - [x] Generator for composite types  - https://github.com/kubernetes/ingress-gce/pull/729
  - [x] Generate all types - https://github.com/kubernetes/ingress-gce/pull/742
  - [x] Integrate composites -  https://github.com/kubernetes/ingress-gce/pull/788
- [x] FrontendConfig
  - [x] Scaffolding - https://github.com/kubernetes/ingress-gce/pull/753
  - [x] Integration (No longer scoped for this project)
- [x] Integrate L7-ILB - https://github.com/kubernetes/ingress-gce/pull/789
- [x] e2e Tests for L7-ILB

/assign

**Comment by spencerhance** [comment]
Current tracking list is out of date but the feature has been merged into master

**Comment by mgoodness** [comment]
Any idea when this will be available as a managed service for GKE?

**Comment by rramkumar1** [comment]
@mgoodness This will be shipping as part of our 1.7 release. We will be adding formal release notes shortly.

**Comment by whyman** [comment]
1.7 and 1.8 seem to be tagged now, but I cant find any information on how to use this functionality?

**Comment by inductor** [comment]
+1

**Comment by inductor** [comment]
Same here. How can I exactly use this feature?

https://cloud.google.com/load-balancing/docs/l7-internal/set-up-gke-pods is not very imformative

**Comment by rushrecon** [comment]
> Same here. How can I exactly use this feature?
> 
> https://cloud.google.com/load-balancing/docs/l7-internal/set-up-gke-pods is not very imformative

You, probably, already find an answer, but someone who will ggl this topic may find the next link useful: [Summary of internal Ingress annotations](https://cloud.google.com/kubernetes-engine/docs/how-to/internal-load-balance-ingress#summary_of_internal_ingress_annotations)

**Comment by spencerhance** [comment]
Hi All, Thanks for your interest.  Internal L7 Load Balancing with Ingress is currently in Beta:

https://cloud.google.com/kubernetes-engine/docs/concepts/ingress-ilb
https://cloud.google.com/kubernetes-engine/docs/how-to/internal-load-balance-ingress

**Comment by cnelson** [comment]
@spencerhance Does the GKE cluster need to be a specific version to use this beta feature?  I've followed the instructions, but the resources are never provisioned and there are no events when describing the resource.

**Comment by spencerhance** [comment]
@cnelson the minimum version is 1.16.0-gke.10 which means you must use rapid channel as per the documentation.  Although the beta should be available in other channels in the coming weeks
